version:  '3'
services:
  master:
    image: cluster-hadoop
    container_name: hadoop-master
    networks:
      cluster-network:
        ipv4_address: 172.20.0.2
        aliases:
          - hadoop-master
    volumes: 
      - ../data/:/data
      - ./:/hadoop
    extra_hosts:
      - "slave1:172.20.0.3"
      - "slave2:172.20.0.4"
    hostname: master
    environment:
      ROLE: master

  slave1:
    image: cluster-hadoop
    container_name: hadoop-slave1
    networks:
      cluster-network:
        ipv4_address: 172.20.0.3
        aliases:
          - hadoop-slave1
    volumes: 
      - ../data/:/data
      - ./:/hadoop
    extra_hosts:
      - "master:172.20.0.2"
      - "slave2:172.20.0.4"
    hostname: slave1
    environment:
      ROLE: slave

  slave2:
    image: cluster-hadoop
    container_name: hadoop-slave2
    networks:
      cluster-network:
        ipv4_address: 172.20.0.4
        aliases:
          - hadoop-slave2
    volumes: 
      - ../data/:/data
      - ./:/hadoop
    extra_hosts:
      - "master:172.20.0.2"
      - "slave1:172.20.0.3"
    hostname: slave2
    environment:
      ROLE: slave

networks:
  cluster-network:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
